version: '2.1'

services:

  neurosynth:
    build: .
    restart: always
    ports:
      - "8000"
    volumes:
      - .:/code
      - /data:/data:rw
      - /logs:/logs:rw
    working_dir: /code
    command: /code/scripts/docker_startup.sh
    depends_on:
      - db
      - redis

  db:
    restart: always
    image: postgres:10.4
    expose:
      - '5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=neurosynth
      - POSTGRES_USER=neurosynth

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - ./nginx/data/certbot/conf:/etc/letsencrypt
      - ./nginx/data/certbot/www:/var/www/certbot
    volumes_from:
      - neurosynth
    depends_on:
      - neurosynth
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  redis:
    restart: always
    image: redis:latest
    sysctls:
      net.core.somaxconn: '511'

  worker:
    build: .
    restart: always
    ports:
      - "8000"
    working_dir: /code
    command: /code/scripts/run_celery.sh
    volumes_from:
      - neurosynth
    depends_on:
      - db
      - redis

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/data/certbot/conf:/etc/letsencrypt
      - ./nginx/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  postgres-data:
  redis-data:
